# Generated by Django 3.1.1 on 2021-05-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_city', models.CharField(max_length=60)),
                ('company_state', models.CharField(max_length=15)),
                ('company_description', models.TextField()),
                ('company_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('job_link', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
