# Generated by Django 3.1.1 on 2021-05-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
