# Generated by Django 3.1.1 on 2020-11-04 09:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0002_auto_20201103_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
