# Generated by Django 3.1.1 on 2021-05-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0002_delete_greeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
