# Generated by Django 3.1.1 on 2021-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0007_auto_20201116_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
