# Generated by Django 3.1.1 on 2021-01-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0009_auto_20210122_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_added',
        ),
    ]
