# Generated by Django 3.1.1 on 2021-01-22 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0010_remove_document_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 22, 22, 45, 26, 210057, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
